### ISSUE TITLE
Black screen on standalone build

### ISSUE THREAD

**Issue by nxrighthere** [gokselgoktas/temporal-anti-aliasing#7]
In Editor works fine.
Unity 5.4.1p1

**Comment by gokselgoktas** [comment]
`Shader.Find()` only looks for shaders under `Resources` in a standalone build. Either always include the shader in the build or wait until I update all my repos to place the shaders under `Resources`.

**Comment by gokselgoktas** [comment]
All of my repos updated to use `Resources` for storing ... well, resources. 🎱
